/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-11-15 at 11:32:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.icumn7abiu.battery.model;

/**
 * Model definition for UpdateReq.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the battery. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UpdateReq extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("DeviceId")
  private java.lang.String deviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("DeviceName")
  private java.lang.String deviceName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Histories")
  private java.util.List<History> histories;

  static {
    // hack to force ProGuard to consider History used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(History.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }

  /**
   * @param deviceId deviceId or {@code null} for none
   */
  public UpdateReq setDeviceId(java.lang.String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceName() {
    return deviceName;
  }

  /**
   * @param deviceName deviceName or {@code null} for none
   */
  public UpdateReq setDeviceName(java.lang.String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<History> getHistories() {
    return histories;
  }

  /**
   * @param histories histories or {@code null} for none
   */
  public UpdateReq setHistories(java.util.List<History> histories) {
    this.histories = histories;
    return this;
  }

  @Override
  public UpdateReq set(String fieldName, Object value) {
    return (UpdateReq) super.set(fieldName, value);
  }

  @Override
  public UpdateReq clone() {
    return (UpdateReq) super.clone();
  }

}
