/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-02-01 at 15:41:07 UTC 
 * Modify at your own risk.
 */

package com.appspot.icumn7abiu.batteryservice.model;

/**
 * Model definition for Battery.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the batteryservice. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Battery extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Charging")
  private java.lang.Boolean charging;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer battery;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime time;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCharging() {
    return charging;
  }

  /**
   * @param charging charging or {@code null} for none
   */
  public Battery setCharging(java.lang.Boolean charging) {
    this.charging = charging;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getBattery() {
    return battery;
  }

  /**
   * @param battery battery or {@code null} for none
   */
  public Battery setBattery(java.lang.Integer battery) {
    this.battery = battery;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public Battery setTime(com.google.api.client.util.DateTime time) {
    this.time = time;
    return this;
  }

  @Override
  public Battery set(String fieldName, Object value) {
    return (Battery) super.set(fieldName, value);
  }

  @Override
  public Battery clone() {
    return (Battery) super.clone();
  }

}
