/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2016-01-10 at 09:22:12 UTC 
 * Modify at your own risk.
 */

package com.appspot.icumn7abiu.batteryservice.model;

/**
 * Model definition for UpdateReq.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the batteryservice. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UpdateReq extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Device")
  private Device device;

  /**
   * @return value or {@code null} for none
   */
  public Device getDevice() {
    return device;
  }

  /**
   * @param device device or {@code null} for none
   */
  public UpdateReq setDevice(Device device) {
    this.device = device;
    return this;
  }

  @Override
  public UpdateReq set(String fieldName, Object value) {
    return (UpdateReq) super.set(fieldName, value);
  }

  @Override
  public UpdateReq clone() {
    return (UpdateReq) super.clone();
  }

}
